services:
  exemploDocker:
    image: exemploDocker/app-node:1.0
    container_name: app-node
    networks:
      - compose-bridge
    ports:
      - "8081:6000"

networks:
  compose-bridge:
    driver: bridge
